name: Build and Test ASP.NET Web App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'

    - name: Install dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs:  build-and-test

    steps:
    - name: Azure Login
      uses: Azure/login@v2
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - name: Deploy Bicep file
      run: |
        az deployment group create \
          --resource-group Demo65191 \
          --template-file arm/demowebapp-arm.template.bicep \
          --parameters arm/demowebapp-arm.parameter.json
        
